apiVersion: apps/v1
kind: Deployment
metadata:
  name: subservice2
  labels:
    app: subservice2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subservice2
  template:
    metadata:
      labels:
        app: subservice2
    spec:
      containers:
        - name: subservice2-container
          image: ebutdev/subservice2:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: subservice2-service
spec:
  selector:
    app: subservice2
  ports:
    - port: 8080
      nodePort: 30002
  type: NodePort
