global:
  scrape_interval: 15s  # Her 15 saniyede bir metrikleri çek

scrape_configs:
  - job_name: 'spring-boot-app'  # Uygulamanızın adı
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Uygulamanızın adresi


  - job_name: 'node-exporter' # Node Exporter'ın adı
    scrape_interval: 5s
    static_configs:
      - targets: [ 'node-exporter:9100' ]  # Node Exporter'ın çalıştığı port