spring:
  application:
      name: microservice2

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus


  tracing:
    enabled: true
    sampling:
      probability: 1.0


server:
#  port: 8081
  error:
    include-stacktrace: never # Stacktrace'i asla göstermez